### ISSUE TITLE
SECURITY: Admin markus API key is leaked through "ps aux"

### ISSUE THREAD

**Issue by ColinChartier** [MarkUsProject/markus-autotesting#128]
For example, if an admin runs a test script that sleeps for 5 seconds, that scripts arguments (including the admin's API key) are visible as long as it is running to all processes on the machine.

**Comment by ColinChartier** [comment]
Since the test script itself is run as markusworker-(blah), someone can always make a script that calls "cat /proc/(pid of test script)/stack" -- it wouldn't necessarily fix it

**Comment by reidka** [comment]
Really?  It is pretty common practice to send user ids and passwords to another process using stdin.  /proc/<pid>/stack shows the kernel stack, but I'm not sure how you would get arguments out of that.  Pointers would be welcome.

**Comment by ColinChartier** [comment]
There's two levels of permission boundaries at play here)
1. If the credentials are in "ps aux", then any user on the system can see them (this one is the one that can be mitigated with stdin)
2. If the credentials are owned by any process that is run by a user that also runs untrusted code, that untrusted code can inspect its memory and extract them -- for example, in the existing architecture, the worker user is the one that executes the test script (and the test script needs the credentials to upload annotations) and also the one that runs the untrusted code itself.

I think the correct architecture is:
- Server user spawns a process when a test is requested
- Server user runs the test script (with credentials passed on stdin)
- Server user (in test script, the one with the #!/venvs/...) calls "sudo -u (workeruser) (rest of script)" and extracts results from the stdout of the untrusted user process

**Comment by ColinChartier** [comment]
For example, see https://stackoverflow.com/questions/12977179/reading-living-process-memory-without-interrupting-it-proc-kcore-is-an-option -- it wouldn't be hard to grep for [a-zA-Z0-9]{43}=

**Comment by adisandro** [comment]
Colin is right, the problem is having to pass the api_key of the instructor in order for them to customize stuff like uploading feedback files or pyta annotations. Those things should really NOT be executed by the untrusted user, but extracted from the test scripts and done by the server user.

I don't think we want to do sudo -u in the test script, because it forces users to know that level of detail in order to create custom scripts (like you're doing, Colin). We still want them to be able to upload whatever script they want, as long as it prints with a predefined format. Plus, in a distributed setting with many servers, workeruser names may be different.

We had a plan where test scripts (other than custom ones) become obsolete and testers are simply chosen from a dropdown list. In that setting, the instructor could still provide "privileged" code to be executed, such as uploading feedback files. We're going to partly implement it now, by splitting the unprivileged test scripts from the "privileged" code.

**Comment by adisandro** [comment]
Fixed by #129
